all:
  children:

    routers:
      hosts:

        r1:
          ansible_connection: community.docker.docker
          ansible_host: clab-ospf-lab-r1
          router_id: 1.1.1.1
          ospf_networks:
            - 10.0.12.0/30
            - 10.0.31.0/30

        r2:
          ansible_connection: community.docker.docker
          ansible_host: clab-ospf-lab-r2
          router_id: 2.2.2.2
          ospf_networks:
            - 10.0.12.0/30
            - 10.0.23.0/30

        r3:
          ansible_connection: community.docker.docker
          ansible_host: clab-ospf-lab-r3
          router_id: 3.3.3.3
          ospf_networks:
            - 10.0.23.0/30
            - 10.0.31.0/30
