---
- name: Backup network device configurations
  hosts: routers
  gather_facts: false

  tasks:

    - name: Get running configuration
      ansible.builtin.command:
        cmd: vtysh -c "show running-config"
      register: running_config

    - name: Save configuration backup
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ running_config.stdout }}"
        dest: "{{ playbook_dir }}/../backups/{{ inventory_hostname }}/running-config.txt"

